services:
  - docker

# before_script:
  # - docker-compose build

# script:
  # - docker-compose run wscef

env:
  global:
    - secure: "grKVCTHS+fQS/Mz1zOWbA2C4X9JuAXcJ+wEdz8ucLs+L70v7gOcQF8u8Fi6e+PZ9U6ZlB17CNlhk0xsW6qNGWlpJHFsUhb3pgreS/hzUU6+ZLY1+Jv4oiGZ05y6NgR7gHbjjOotzW5s/eP1Dbs4TpDxZwUi7qYedkyBQDhx9DuHz3sxkzE/8yWLqpZkY9Hp7dZv7cK3jmtJ76cXKQwnH1NEkD8GEVTEc6diDF9CpByPI1vV/X5YENniBsBg0F37D+DDreJKGlz3LsBYbg0ipqTdQngULEdVa0QQp37ukWBeKoe7YQmhyYALi8QjILx5exsOXQAuAT93i1bvHDH+tJZyeEwHCSkb+Qas67gQJgKA4OwrNbWd3tCr8QmCxALOxRdad6xHg+tlB1D/saqK5PHh2FzDxKGnLwkRYO58ZzEAyBxvn+EboiNONi1/cMZHJrutah3R0PD//thfY+77K35R3sXPTwxJtH9OvGXCpXGmBe/WwyOmqHNLMTvmYmtSWS5BmUp4nqAe8b8e9IzZqHCwOOKQMzt1AaAh3e+AwecuhbPXjspUUN1JH8ycbtPuOwz8/L8IiwFm6BFqSZMatKUgr6cUgWDUM3WRxqLfHJ1mXRntP3xuwGomZXzqWyPmDJ8ioIROsYrMrbFXfdczEtw4/aEino8O+LLBBmbRAsQ8="
    - secure: "czgavVKbtBsd2776EdRuZiiYq4DN5c54KegacoVJCkEKvZoP36BrVstXltP9fEXEORBJPBGb2yQYoI7tyZlN51YTzyXYqvtQUDcRKdWQ9EmzL6Ra7tSRBr8CoL7sapurPyGf438a1vLOXnUmMRXOhTJ//ydJFRttNbmxU/ZloSaEaIZ8zFViegEg94Xh4M6m0rnms+bdrl0JL0NNNuPr7KQILvDQnv9RA9orFybbU7pw49lGfUY3XP1UhmxpbG9oNVGLhEC9FbYfbKJ1JmTEccxGxslrDV8lSWXvWETvL9QVQ1bWKTp+Lm1vrd1aWrcX0cQuUyT3soIsV+CJgYKJVG3EQCRR//cWu0p9GFC+AUwDc16DGe6+L90U7AaFe+M3UZQZfD7W2hKkJW0o28MwdGoyaZsBqYXjXNLuCG271KLgxqBc47sBrDhd3qfceh2Y+c6DcjEBMcxkZOvXBAIJPNqr2ljyWTcCpBVk/bgn95wXvHzldmabKSzflzeqgONZY6Pmo5IfiMx87Q3r80Q9IoooknyBrQsatThRatEMkERnnK5ew4sKfk0SrAiKPp89kz82TAmfD019/NjRw78bizCDYx7h7q+qKNO1GrIMnX6uI2nFpKSiIINe27FrOWNfkYBvrgpBN0bqq2YtY2xzmnKIRrLwjLJs8EyfVUhsA9k="
    - secure: "VFk1cV9AHIk/eG4ToPX2n9LIEImioiT2Xe9Xr2otFkejo2eh4Z2OSQdhwumMupK794JGKWEjnjtXw+1gYd+xjI81OKk5ViSwpwI59TVhk06CBCmzWGX2vB+KKM7nMAh8mhZdeQLs6LkXfWDMvmHgrh4Z0wqHTlXPbpfdsX05mFa5LJLuWbzznNjYqgx9CE239tM/ZrBo/eDyHcDSxIbwgf8Ty6CBhYRDGm+paE2MABsK24J0KIO90aOXSnPdP6xmPrpboglxf+8aXLdhX44FOgB+bIgDY2Yvcg9r8j8J+LYV1CPbtMzX+Q8WPGJsZHkHCZ5jpuniLcVZmA3FaL/T0opMzrmFgicdd7VvcXn+wichPlGI7tefJiumOJ7zdef/3wSGdvDN0GlpcNII/Av284Itkr/eAwoCv5oK7oz3FrGSoXFSQ9wXm8Fmz5NMht9UYGx11XXOuWKFk7D2Ojk02bHlTsLjdJAf+wn6viEpHnzFki1wiHPc7PltIm0KN3QPXWrVjfkRWBfJb1XGs2prLu0+9V78byOjdY+X++GIGWKg78TYlFt0rGMlaxKk2Ptl+CcTbb8yNun/l66qt3HJ76aj5uUIi+leRf1CtHHRFSv+eB+4Y+maEdpVgc1uVJ62/eGhEeEkIxLWUAZUIfCpq2IlQajVnixiIu1YVYZ5HSw="

before_script:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - export REPO=farribeiro/wscef-docker
  - export COMMIT=latest
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker-compose build
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
