services:
  - docker

before_script:
  - docker-compose build

# script:
  # - docker-compose run wscef

env:
  global:
  - secure: Ah8HUTWw5/0gxw6IY3Hrt1hlF5EbiPod8HD3vkdhK0CNMhh0cdHxIAM2nC0kC8cIsxihZJPQHerZq6wfnnKzJP8zmbTFkpI9t8vvRo0UUh9OVvxDnfCj/Pb/Uf2oqf7+CSZDxEdwU8IoKHgBR13hPb4UjKU00uO9q6iB2lEPav2JBDRVLrMxcpTTzwbMv8PSdySkXg8GqlY1iIB6NFmjPlOS4v9ei0qSpEgX9rGb7KXkuAsXrioZGghpWeyAznMcfeIYZJfjoSUs1HR6SDL/Kuv9P/oPD2uJ25+Mh78gerhwNLMYdGC5oLW2uGNT1v2fmK8SBCN3B3VcZrTnE0p/7mIkrzkDnzWq6ldCo38Wpv/MG44g/N4u1GikkAzrofd1JTk/m5s3n4C9XsarnySqBCDs2qb+sjC7Fb/8ij99qNuYIe1TPOkVif3cCXqiPaWnIbiSi2DCLgombeB+LF9lOxKCGxcFfbaPMQcHzIKJCDxacUKKUy3iUhwpfwwU8DBSTXNsTyWuqj0UpSQrxP9pZKKpGMlVjjUzUjpObvQEhH/vkr7ugVuvAX8ORqCjLGRuPgfNE1F4lx9vDa8e4Vh0NedxROI4ZtTtSn4GG6jH6vWDIMZMEiK33KVmWDEPa58WJyfPrdQ9dEL/JV5JTK1sH6Mi5c9Stk7XLCmQ9XkXoGM=
  - secure: ZHCB/2NeHoRGwPXFzCI0v8OqS2U8dJFxMFVDy/Amu0qakl1LvqkU1Z9lyWv/67tFkl7jzVB35nja+PcE04WxEDK5hGucXUMiMhi8z/bDCC6iNKRH1w4veoMNg88PsHVvGVxJ1jxda0oAa+GlbFP6u0qk4AqIlOOkVc1E9G556pk4+9D0kBhzzgcHHnovEtVy0a6KT/sjXjU2jMlOdaOrwzOWIm+oSvJjAnilWzDRW9d5T8qItnK3GHOL7fF3Vg3pYNp8YTiuzLYkPZZj8MWgqUCmVky5S23aTbwiC9Lt3GG54zQMc/YL/xrTLEvOWoxdLMXzAGYN9Rfngu4U2RjMeTg4S8+FeKNJmPGwzhTG7RbARKPmtylrDUAnsaNy8gzJ6PDtLN+465r/C1YmTwzrRzI6iETONfp0VjVPEg/KAiL7U3TOmMkpnzaGNDXzI2skRZvWnewf/PI4BxFSEdP1q63AQBZOQAFqE/3jjB+DUJ+S+lJQ4MyUZIX4JgKyoJBFcqWfIAZOxfveakE8hm9O3KHDSNpYWbtE0y8/2fUGw9OUYyh1sN7P92lOIt2U+00Co4OLLXq+ruB7QMKMt5bX3qA8eg1Apippzsrfy+GQMzbZell85HUm5vK3FSxrLAc+Bl7Vtg3Agk4TDdyEyf7m92FOUI50gTa1pQlJI3fqLsw=
  - secure: "ltYxTDGt4mVwEnNaKAvEetHVqkaricZMI/3vsEdscUfJRfCd2aLz3QGw/73ycPxIxTek/tjpChCauyoHubX1ERoIW4zmzvKgHlC643CV2u8CrXLRm1G1HAabYtJV7SScvm3ra1b/8CQUEKEn1mtfJbScQ3+SsPpd1nPOA05PLWzU4rrou6VpL0V9My47RQaNGqer9fXRInNfhqsYIK9oMqVrW8KF6gRatK6SwAZjHh3I+GqYc90n9j79WJ9KQjSHYbZwhcRIB2FusQnBLYq/RHngonv1u7LZy+Zb1t9IMQQ4onzrvmXZRnpx9YAUN0EehBG2wm9yvD7otFMVvK3TosmiBdYrZgZCWU0VOc25hgf3/DszgMagIH9vB5KYxKLfQAlAEm9mLU/5tvk4sVjYJhkaXwoaYwNrUvi+7sHXt2MCjp14Lj7lvNwbd0ksNgNrHHNEX22bfBv96wMb6RMkwrXYmDGgxxFd15KDquWiAB5iaB5w6Csvfkf+ThsXom+fpnZTSleVXPz/9tLIvhG6JqHxnidqQ4aRS2Ue3LmE/eEQaSiny3hJSejPpwykdwVNa09dSf00r1nZ393vAtQeVZSIHnUj0jDQcpMosxbZ4GhXx5wap/XBcIEfJKzftyZVORIoGdFh9iD2/GaYu7HN7+XRodmoU4ZYQie9f2P+bao="

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=farrbeiro/wscef-docker
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
